name: Test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Run tests
        run: ./test/libs/bats-core/bin/bats test/*.bats
